### ISSUE TITLE
Excuse me, error when running your "Proposed Solution.py"

### ISSUE THREAD

**Issue by zhang123-sys** [jordankzf/human-silhouette-extractor#2]
when running
```
model = torch.hub.load('pytorch/vision:v0.6.0', 'deeplabv3_resnet101', pretrained=True)
```
error:

```
  File "C:\Users\hp\Miniconda3\envs\torch1.10\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by jordankzf** [comment]
Are you running this on the cloud? Something like Google Colab?

**Comment by zhang123-sys** [comment]
Yes, your code is&nbsp;running well




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jordan ***@***.***&gt;; 
发送时间: 2024年1月4日(星期四) 上午10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jordankzf/human-silhouette-extractor] Excuse me, error when running your &quot;Proposed Solution.py&quot; (Issue #2)





 
Are you running this on the cloud? Something like Google Colab?

**Comment by jordankzf** [comment]
Great. Enjoy. For future readers, the error is due to rate limiting which is more likely to be encountered when running this repo on cloud instances.
